{
  imports = [
    ./audio/pavucontrol.nix
    ./battery/acpi.nix
    ./browsers/brave.nix
    ./browsers/chrome.nix
    ./browsers/firefox.nix
    ./cli-tools/atuin.nix
    ./cli-tools/lazydocker.nix
    ./cli-tools/lazygit.nix
    ./cli-tools/starship.nix
    ./cli-tools/yazi.nix
    ./cli-tools/zellij.nix
    ./communicators/discord.nix
    ./core/core-packages.nix
    ./desktop/fonts.nix
    ./desktop/gtk.nix
    ./desktop/wallpapers.nix
    ./desktop/xdg.nix
    ./dev/languages/go.nix
    ./dev/languages/nodejs.nix
    ./dev/drawio.nix
    ./dev/git.nix
    ./dev/neovim.nix
    ./dev/postman.nix
    ./dev/direnv.nix
    ./dev/vscode.nix
    ./disk/baobab.nix
    ./disk/gnome-disk-utility.nix
    ./disk/udiskie.nix
    ./file-managers/nautilus.nix
    ./file-managers/nemo.nix
    ./file-managers/thunar.nix
    ./gaming/heroic.nix
    ./gaming/lutris.nix
    ./gaming/wine.nix
    ./music/spotify.nix
    ./network/network-manager.nix
    ./notes/gnome-text-editor.nix
    ./notes/obsidian.nix
    ./notifications/dunst.nix
    ./secrets/polkit-gnome.nix
    ./secrets/seahorse.nix
    ./shells/bash.nix
    ./terminals/alacritty.nix
    ./terminals/ghostty.nix
    ./tools/evince.nix
    ./tools/gimp.nix
    ./tools/gnome-system-monitor.nix
    ./tools/libreoffice.nix
    ./tools/okular.nix
    ./tools/qalculate.nix
    ./tools/qbittorrent.nix
    ./tools/zathura.nix
    ./wm-wayland/flameshot.nix
    ./wm-wayland/fuzzel.nix
    ./wm-wayland/niri.nix
    ./wm-wayland/ozone-fix.nix
    ./wm-wayland/swaybg.nix
    ./wm-wayland/swaylock.nix
    ./wm-wayland/swaync.nix
    ./wm-wayland/waybar.nix
    ./wm-wayland/wdisplays.nix
    ./wm-wayland/wl-clipboard.nix
    ./wm-x11/arandr.nix
    ./wm-x11/feh.nix
    ./wm-x11/flameshot.nix
    ./wm-x11/high-dpi.nix
    ./wm-x11/picom.nix
    ./wm-x11/pywal.nix
    ./wm-x11/qtile.nix
    ./wm-x11/rofi.nix
    ./wm-x11/xclip.nix
  ];
}
